# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestReshamsgallery():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_reshamsgallery(self):
    # Test name: Resham's gallery
    # Step # | name | target | value
    # 1 | open | /catalog.html | 
    self.driver.get("http://localhost:8000/catalog.html")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | click | id=1 | 
    self.driver.find_element(By.ID, "1").click()
    # 4 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 5 | click | id=txtquantity | 
    self.driver.find_element(By.ID, "txtquantity").click()
    # 6 | click | linkText=Gallery | 
    self.driver.find_element(By.LINK_TEXT, "Gallery").click()
    # 7 | click | id=1 | 
    self.driver.find_element(By.ID, "1").click()
    # 8 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 9 | click | id=txtquantity | 
    self.driver.find_element(By.ID, "txtquantity").click()
    # 10 | type | id=txtquantity | 78
    self.driver.find_element(By.ID, "txtquantity").send_keys("78")
    # 11 | click | css=td:nth-child(1) > input | 
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1) > input").click()
    # 12 | click | css=td:nth-child(1) > input | 
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1) > input").click()
    # 13 | click | linkText=Gallery | 
    self.driver.find_element(By.LINK_TEXT, "Gallery").click()
    # 14 | click | id=2 | 
    self.driver.find_element(By.ID, "2").click()
    # 15 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 16 | click | css=tr:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2)").click()
    # 17 | type | id=txtquantity | 7
    self.driver.find_element(By.ID, "txtquantity").send_keys("7")
    # 18 | click | css=td:nth-child(1) > input | 
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1) > input").click()
    # 19 | click | css=td:nth-child(1) > input | 
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1) > input").click()
    # 20 | click | linkText=Gallery | 
    self.driver.find_element(By.LINK_TEXT, "Gallery").click()
    # 21 | click | id=5 | 
    self.driver.find_element(By.ID, "5").click()
    # 22 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 23 | click | id=txtquantity | 
    self.driver.find_element(By.ID, "txtquantity").click()
    # 24 | type | id=txtquantity | 6
    self.driver.find_element(By.ID, "txtquantity").send_keys("6")
    # 25 | click | css=td:nth-child(1) > input | 
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1) > input").click()
    # 26 | click | css=td:nth-child(1) > input | 
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1) > input").click()
    # 27 | click | css=td:nth-child(1) > input | 
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1) > input").click()
    # 28 | click | css=td:nth-child(1) > input | 
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1) > input").click()
    # 29 | click | css=td:nth-child(3) > input | 
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(3) > input").click()
    # 30 | click | linkText=Gallery | 
    self.driver.find_element(By.LINK_TEXT, "Gallery").click()
    # 31 | click | id=7 | 
    self.driver.find_element(By.ID, "7").click()
    # 32 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 33 | click | id=txtquantity | 
    self.driver.find_element(By.ID, "txtquantity").click()
    # 34 | type | id=txtquantity | 9
    self.driver.find_element(By.ID, "txtquantity").send_keys("9")
    # 35 | click | css=td:nth-child(1) > input | 
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1) > input").click()
  
