// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FlowerTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void flower() {
    // Test name: flower
    // Step # | name | target | value
    // 1 | open | /catalog.html | 
    driver.get("http://localhost:8000/catalog.html");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | linkText=Gallery | 
    driver.findElement(By.linkText("Gallery")).click();
    // 4 | click | id=1 | 
    driver.findElement(By.id("1")).click();
    // 5 | click | css=button | 
    driver.findElement(By.cssSelector("button")).click();
    // 6 | click | id=txtquantity | 
    driver.findElement(By.id("txtquantity")).click();
    // 7 | type | id=txtquantity | 5
    driver.findElement(By.id("txtquantity")).sendKeys("5");
    // 8 | click | css=td:nth-child(1) > input | 
    driver.findElement(By.cssSelector("td:nth-child(1) > input")).click();
    // 9 | click | linkText=Gallery | 
    driver.findElement(By.linkText("Gallery")).click();
    // 10 | click | id=2 | 
    driver.findElement(By.id("2")).click();
    // 11 | click | css=button | 
    driver.findElement(By.cssSelector("button")).click();
    // 12 | click | id=txtquantity | 
    driver.findElement(By.id("txtquantity")).click();
    // 13 | type | id=txtquantity | 012
    driver.findElement(By.id("txtquantity")).sendKeys("012");
    // 14 | click | css=td:nth-child(1) > input | 
    driver.findElement(By.cssSelector("td:nth-child(1) > input")).click();
    // 15 | click | css=td:nth-child(1) > input | 
    driver.findElement(By.cssSelector("td:nth-child(1) > input")).click();
  }
}
